dicom-series:
  empty-plastic: '/Users/artoews/root/data/mri/240202/14446_dicom/Series24'
  empty-plastic-2: '/Users/artoews/root/data/mri/240202/14446_dicom/Series25'
  empty-metal: '/Users/artoews/root/data/mri/240202/14446_dicom/Series30'
  empty-metal-2: '/Users/artoews/root/data/mri/240202/14446_dicom/Series31'
  lattice-plastic: '/Users/artoews/root/data/mri/240202/14446_dicom/Series14'
  lattice-metal: '/Users/artoews/root/data/mri/240202/14446_dicom/Series18'
  lattice-plastic-hr: '/Users/artoews/root/data/mri/240202/14446_dicom/Series4'

params:
  slice: [[38, 158], [66, 186], [12, 48]]
  IA-thresh-relative: 0.3
  GD-thresh-pixels: 1
  psf-window-size: [40, 40, 20]
  psf-stride: 5
  num-workers: 8
