dicom-series:
  structured-plastic-reference: '/Users/artoews/root/data/mri/240304/14660_dicom/Series2'
  structured-plastic: '/Users/artoews/root/data/mri/240304/14660_dicom/Series4'
  structured-metal: '/Users/artoews/root/data/mri/240304/14660_dicom/Series7'
  uniform-plastic: '/Users/artoews/root/data/mri/240304/14660_dicom/Series13'
  uniform-plastic-2: '/Users/artoews/root/data/mri/240304/14660_dicom/Series14'
  uniform-metal: '/Users/artoews/root/data/mri/240304/14660_dicom/Series19'
  uniform-metal-2: '/Users/artoews/root/data/mri/240304/14660_dicom/Series20'

params:
  slice: [[38, 158], [66, 186], [12, 48]]
  IA-thresh-relative: 0.3
  GD-thresh-pixels: 1
  psf-window-size: [14, 14, 10]
  psf-stride: 1
  num-workers: 8
